log_level: "debug"
base_url: "/"
listen: "0.0.0.0:8080"
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  db_name: "web_base_test"
  ssl_mode: "disable"
  time_zone: "Asia/Shanghai"
