version: "3"
services:
  postgres:
    container_name: wx-postgres
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=wx_backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    container_name: wx-redis
    image: redis:latest
    restart: always
    command: ["redis-server", "--requirepass","redis"]

  backend:
    container_name: wx-backend
    build:
      context: . 
      dockerfile: Dockerfile 
    restart: always
    links:
      - redis:redis
      - postgres:postgres
    depends_on:
      - postgres
    volumes:
      - ./data/static:/static
      - ./data/logs:/logs
    ports:
      - "0.0.0.0:9000:8080"

